import test from 'node:test';
import assert from 'node:assert/strict';
import { inferGearFromMeasurements } from '../lib/photo-inference.ts';
import type { ConfirmedMeasurement, InferredGearKind, PhotoInferenceInput } from '../lib/photo-inference.ts';
import { deriveGear, defaultGearParams } from '../lib/gearMath.ts';

const fact = <T>(value: T): ConfirmedMeasurement<T> => ({ value, source: 'measurement' });
const base = (change: Partial<PhotoInferenceInput> = {}): PhotoInferenceInput => ({
  kind: fact('spur'), profileType: fact('involute'), toothCount: fact(24), tipDiameterMm: fact(52),
  tipDiameterMethod: fact('tip_circle'), pressureAngleDeg: fact(20), profileShift: fact(0), standardAddendum: fact(true), ...change,
});
const close = (actual: number, expected: number, tolerance = 1e-10) => assert.ok(Math.abs(actual - expected) <= tolerance, `${actual} != ${expected} ± ${tolerance}`);
const ready = (input: PhotoInferenceInput) => {
  const result = inferGearFromMeasurements(input);
  assert.equal(result.status, 'ready', JSON.stringify(result));
  if (result.status !== 'ready') throw Error('Expected ready result');
  return result;
};

test('KHK published spur example da=78,z=24 identifies m=3 without standard-series snapping', () => {
  const result = ready(base({ tipDiameterMm: fact(78) }));
  close(result.parameters.module, 3); close(result.calculation.pitchDiameterMm!, 72);
  assert.equal(result.parameters.helixAngleDeg, 0);
  assert.equal(result.provenance.helixAngleDeg.status, 'derived');
  assert.equal(result.provenance.module.status, 'derived');
  assert.equal(result.provenance.tipDiameterMm.status, 'confirmed');
  close(ready(base({ tipDiameterMm: fact(52.13) })).parameters.module, 2.005);
});

test('KHK tables 4.5 and 4.6 independently check profile-shift signs', () => {
  // Published examples, not dimensions generated by our forward kernel.
  const external = ready(base({ toothCount: fact(12), tipDiameterMm: fact(45.6), profileShift: fact(.6) }));
  close(external.parameters.module, 3); close(external.calculation.pitchDiameterMm!, 36);
  const internal = ready(base({ kind: fact('internal'), tipDiameterMm: fact(69.096), profileShift: fact(.516) }));
  close(internal.parameters.module, 3); close(internal.calculation.pitchDiameterMm!, 72);
  assert.match(internal.calculation.formula, /− 2\(1 − x\)/);
});

test('KHK table 4.13 helical rack example pt=8, beta=10°57′49″ recovers mn=2.5 within printed rounding', () => {
  const result = ready(base({ kind: fact('helical-rack'), helixAngleDeg: fact(10 + 57 / 60 + 49 / 3600), transversePitchMm: fact(8), toothCount: undefined }));
  close(result.parameters.module, 2.5, 2e-6);
  close(result.calculation.transverseModuleMm, 8 / Math.PI);
  assert.equal(result.calculation.pitchDiameterMm, null);
  assert.equal(result.parameters.teeth, undefined, 'rack pitch cannot establish rack length');
});

test('seven families recover independent analytic dimensions and pass the forward kernel', () => {
  const cases: { kind: InferredGearKind; z: number; beta: number; shift: number; m: number }[] = [
    { kind: 'spur', z: 37, beta: 0, shift: -.2, m: 1.25 },
    { kind: 'helical', z: 24, beta: 30, shift: .3, m: 2 },
    { kind: 'herringbone', z: 36, beta: -25, shift: .2, m: 1.5 },
    { kind: 'internal', z: 80, beta: 0, shift: .3, m: 2.5 },
    { kind: 'internal-helical', z: 80, beta: -30, shift: .1, m: 2 },
    { kind: 'rack', z: 12, beta: 0, shift: .1, m: 1.75 },
    { kind: 'helical-rack', z: 10, beta: 20, shift: .2, m: 3 },
  ];
  for (const row of cases) {
    const cos = Math.cos(row.beta * Math.PI / 180), isRack = row.kind.includes('rack'), isInternal = row.kind.includes('internal');
    // Independent basic reference-pitch geometry, before invoking the forward kernel.
    const d = row.m * row.z / cos;
    const da = d + (isInternal ? -2 * row.m * (1 - row.shift) : 2 * row.m * (1 + row.shift));
    const input = base({ kind: fact(row.kind), toothCount: fact(row.z), helixAngleDeg: fact(row.beta), profileShift: fact(row.shift),
      tipDiameterMm: isRack ? undefined : fact(da), transversePitchMm: isRack ? fact(Math.PI * row.m / cos) : undefined });
    const result = ready(input);
    close(result.parameters.module, row.m);
    close(result.calculation.transverseModuleMm, row.m / cos);
    const forward = deriveGear({ ...defaultGearParams, ...result.parameters, teeth: row.z, bore: 0, backlash: 0 });
    if (isRack) close(forward.dimensions.transverseCircularPitch, input.transversePitchMm!.value);
    else close(forward.dimensions.tipDiameter, da);
  }
});

test('diameter does not identify pressure angle; calculated module remains partial', () => {
  const result = inferGearFromMeasurements(base({ pressureAngleDeg: undefined }));
  assert.equal(result.status, 'missing'); assert.equal(result.parameters, null);
  close(result.calculation!.normalModuleMm, 2);
  assert.equal(result.provenance.pressureAngleDeg.status, 'missing');
  assert.ok(result.missingQuestions.some(q => q.id === 'pressureAngleDeg'));
  for (const angle of [14.5, 20, 25]) {
    const candidate = ready(base({ pressureAngleDeg: fact(angle) }));
    assert.equal(candidate.parameters.pressureAngleDeg, angle);
    close(candidate.parameters.module, 2);
  }
});

test('silhouette proposes alternative families and never confirms straight teeth or an involute', () => {
  const external = inferGearFromMeasurements({ silhouette: 'external_circular' });
  assert.equal(external.status, 'missing'); assert.equal(external.calculation, null);
  assert.deepEqual(external.hypotheses.map(h => h.kind), ['spur', 'helical', 'herringbone']);
  assert.equal(external.provenance.kind.status, 'missing');
  assert.equal(external.provenance.profileType.status, 'missing');
  for (const h of external.hypotheses) assert.ok(!('module' in h));
  const ring = inferGearFromMeasurements({ silhouette: 'internal_ring' });
  assert.deepEqual(ring.hypotheses.map(h => h.kind), ['internal', 'internal-helical']);
  const rack = inferGearFromMeasurements({ silhouette: 'linear_rack' });
  assert.deepEqual(rack.hypotheses.map(h => h.kind), ['rack', 'helical-rack']);
  assert.equal(inferGearFromMeasurements({}).hypotheses.length, 7);
});

test('all circular measurement gates stay missing instead of supplying numerical defaults', () => {
  for (const field of ['kind', 'profileType', 'toothCount', 'tipDiameterMm', 'tipDiameterMethod', 'profileShift', 'standardAddendum'] as const) {
    const result = inferGearFromMeasurements(base({ [field]: undefined }));
    assert.equal(result.status, 'missing', field);
    assert.equal(result.parameters, null, field);
    assert.equal(result.calculation, null, field);
    assert.ok(result.missingQuestions.some(q => q.id === field), field);
  }
  const tilted = inferGearFromMeasurements(base({ kind: fact('helical'), helixAngleDeg: undefined }));
  assert.equal(tilted.status, 'missing'); assert.equal(tilted.calculation, null);
  assert.ok(tilted.missingQuestions.some(q => q.id === 'helixAngleDeg'));
});

test('rack module derives from pitch independently of x, addendum and count, but does not invent them', () => {
  const result = inferGearFromMeasurements(base({ kind: fact('rack'), toothCount: undefined, profileShift: undefined, standardAddendum: undefined, transversePitchMm: fact(2 * Math.PI) }));
  assert.equal(result.status, 'missing'); close(result.calculation!.normalModuleMm, 2);
  assert.equal(result.parameters, null);
  assert.equal(result.provenance.profileShift.status, 'missing');
  assert.equal(result.provenance.toothCount.status, 'missing');
  assert.ok(!result.missingQuestions.some(q => q.id === 'toothCount'));
});

test('odd teeth and uncorrected caliper spans cannot masquerade as tip-circle diameters', () => {
  for (const kind of ['spur', 'internal', 'helical', 'internal-helical'] as const) {
    const data = base({ kind: fact(kind), toothCount: fact(35), tipDiameterMm: fact(80), helixAngleDeg: kind.includes('helical') ? fact(20) : undefined });
    const result = inferGearFromMeasurements({ ...data, tipDiameterMethod: fact('opposed_tips') });
    assert.equal(result.status, 'missing'); assert.equal(result.calculation, null);
    assert.ok(result.missingQuestions.some(q => q.id === 'tipDiameterMethod'));
    assert.equal(ready({ ...data, tipDiameterMethod: fact('tip_circle') }).status, 'ready');
  }
  assert.equal(ready(base({ tipDiameterMethod: fact('opposed_tips') })).status, 'ready');
  for (const z of [24, 25]) {
    const result = inferGearFromMeasurements(base({ toothCount: fact(z), tipDiameterMethod: fact('uncorrected_caliper_span') }));
    assert.equal(result.status, 'missing'); assert.equal(result.calculation, null);
  }
});

test('shifted-pair tip shortening and noninvolute profiles require other geometry', () => {
  for (const input of [base({ standardAddendum: fact(false) }), base({ profileType: fact('cycloidal') }), base({ profileType: fact('other') })]) {
    const result = inferGearFromMeasurements(input);
    assert.equal(result.status, 'rejected'); assert.equal(result.calculation, null); assert.equal(result.parameters, null);
    assert.ok(result.issues.length);
  }
});

test('invalid finite, integer, sign and model-range inputs are rejected without NaN output', () => {
  const changes: Partial<PhotoInferenceInput>[] = [];
  for (const value of [0, -1, NaN, Infinity]) {
    changes.push({ tipDiameterMm: fact(value) });
    changes.push({ kind: fact('rack'), transversePitchMm: fact(value) });
  }
  for (const value of [0, 5, 251, 24.5, NaN, Infinity]) changes.push({ toothCount: fact(value) });
  for (const value of [-.81, 1.01, NaN]) changes.push({ profileShift: fact(value) });
  for (const value of [0, 9.9, 35.1, Infinity]) changes.push({ pressureAngleDeg: fact(value) });
  for (const value of [-46, 46, NaN]) changes.push({ kind: fact('helical'), helixAngleDeg: fact(value) });
  changes.push({ tipDiameterMm: fact(.001) }, { tipDiameterMm: fact(1e9) });
  for (const change of changes) {
    const result = inferGearFromMeasurements(base(change));
    assert.equal(result.status, 'rejected', JSON.stringify(change));
    assert.equal(result.calculation, null); assert.equal(result.parameters, null);
  }
  close(ready(base({ tipDiameterMm: fact(2.6) })).parameters.module, .1);
  close(ready(base({ tipDiameterMm: fact(780) })).parameters.module, 30);
});

test('unknown sources and kind/helix contradictions do not become accepted facts', () => {
  const badSource = base({ pressureAngleDeg: { value: 20, source: 'ai_guess' as 'measurement' } });
  assert.equal(inferGearFromMeasurements(badSource).status, 'rejected');
  for (const data of [base({ helixAngleDeg: fact(20) }), base({ kind: fact('helical'), helixAngleDeg: fact(0) })]) {
    const result = inferGearFromMeasurements(data);
    assert.equal(result.status, 'rejected');
    assert.ok(result.issues.some(i => i.code === 'HELIX_KIND_CONFLICT'));
  }
});

test('provenance preserves explicit source and does not mutate the supplied facts', () => {
  const input = base({ tipDiameterMm: { value: 52, source: 'drawing', note: 'Detail A, da' } });
  const before = structuredClone(input);
  const result = ready(input);
  assert.deepEqual(input, before);
  assert.deepEqual(result.provenance.tipDiameterMm, { status: 'confirmed', value: 52, source: 'drawing', note: 'Detail A, da' });
  if (result.provenance.module.status !== 'derived') throw Error('Expected derived module');
  assert.ok(result.provenance.module.inputs.includes('profileShift'));
});
