import type {GearMesh,MeshValidation} from './gearMath';
export type PrintSettings={bedX:number;bedY:number;bedZ:number;nozzle:number;lineWidth:number;layer:number;material:string};
export const defaultPrintSettings:PrintSettings={bedX:256,bedY:256,bedZ:256,nozzle:.4,lineWidth:.45,layer:.16,material:'PETG'};
export type PrintCheck={id:string;label:string;status:'pass'|'warning'|'fail';detail:string};
export function assessPrint(mesh:GearMesh,validation:MeshValidation,s:PrintSettings){
 const values=[s.bedX,s.bedY,s.bedZ,s.nozzle,s.lineWidth,s.layer];if(values.some(x=>!Number.isFinite(x)||x<=0))throw new Error('Размеры стола, сопла, линии и слоя должны быть положительными.');
 const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<mesh.positions.length;i++) {const a=i%3;min[a]=Math.min(min[a],mesh.positions[i]);max[a]=Math.max(max[a],mesh.positions[i]);}const size=max.map((v,i)=>v-min[i]);
 const fit=(size[0]+10<=s.bedX&&size[1]+10<=s.bedY)||(size[1]+10<=s.bedX&&size[0]+10<=s.bedY);const d=mesh.dimensions,p=mesh.params;const tip=d.tipThickness;
 const wall=p.kind==='internal'?(p.rimThickness??3*p.module):p.kind==='rack'?(p.rackBaseHeight??3*p.module):(d.rootDiameter-p.bore)/2;
 const fmt=(n:number)=>n.toLocaleString('ru-RU',{maximumFractionDigits:2});
 const checks:PrintCheck[]=[{id:'mesh',label:'Замкнутая сетка',status:validation.valid?'pass':'fail',detail:validation.valid?`${validation.triangles.toLocaleString('ru-RU')} треугольников; рёбра и ориентация проверены. Самопересечения отдельно не проверялись.`:'Сетка не прошла проверку.'},{id:'bed',label:'Габариты на столе',status:fit&&size[2]<=s.bedZ?'pass':'fail',detail:`${size.map(fmt).join(' × ')} мм. По 5 мм запаса по краям, ось колеса вертикальна.`},{id:'tip',label:'Толщина вершины зуба',status:tip<s.lineWidth?'fail':tip<2*s.lineWidth?'warning':'pass',detail:`${fmt(tip)} мм / ширина линии ${fmt(s.lineWidth)} мм. Ориентир — минимум две линии; это эвристика для пробной печати.`},{id:'wall',label:'Материал под зубьями',status:wall<s.lineWidth?'fail':wall<2*s.lineWidth?'warning':'pass',detail:`Минимальный радиальный запас или основание ${fmt(wall)} мм.`},{id:'layer',label:'Слой и сопло',status:s.layer<=.8*s.nozzle&&s.lineWidth>=.8*s.nozzle&&s.lineWidth<=1.5*s.nozzle?'pass':'warning',detail:`Слой ${fmt(s.layer)} мм, сопло ${fmt(s.nozzle)} мм. Ориентир слоя ≤ 80% диаметра сопла; ширину линии проверьте в профиле слайсера.`}];
 if(p.kind==='helical'||p.kind==='herringbone')checks.push({id:'overhang',label:'Наклон и опоры',status:'warning',detail:'Проверьте нависания в слайсере. Следы опор на рабочих боковинах могут ухудшить зацепление.'});
 if(mesh.warnings.some(w=>w.code==='UNDERCUT'))checks.push({id:'undercut',label:'Подрезание зуба',status:'warning',detail:'Есть риск подрезания. Проверьте профиль и ответное колесо до изготовления.'});
 return {status:checks.some(c=>c.status==='fail')?'fail':checks.some(c=>c.status==='warning')?'warning':'pass',size,checks,volumeMm3:validation.signedVolume,material:s.material,disclaimer:'Это геометрическая оценка пробной печати. Прочность, момент, ресурс, точность посадок и работа с ответной деталью не подтверждены.'};
}
