"use client";
import {useRef,useState} from 'react';
import { Camera, Upload, ScanLine, Check, ArrowRight, AlertTriangle } from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {analyzeGearImage,deriveMeasuredSpurParameters,type PhotoAnalysis} from '@/lib/photo-analysis';
import type {GearParams} from '@/lib/gearMath';
export function PhotoWizard({onApply,onManual}:{onApply:(p:Partial<GearParams>,source:string)=>void;onManual:()=>void}){
 const fileInput=useRef<HTMLInputElement>(null); const [image,setImage]=useState<string|null>(null),[analysis,setAnalysis]=useState<PhotoAnalysis|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const [teeth,setTeeth]=useState(''),[diameter,setDiameter]=useState(''),[type,setType]=useState('unknown'),[standard,setStandard]=useState(false),[measured,setMeasured]=useState(false);const [width,setWidth]=useState('10'),[bore,setBore]=useState('8');
 const loadFile=async(file?:File)=>{if(!file)return;setError('');setAnalysis(null);setImage(null);setStandard(false);setMeasured(false);setTeeth('');setType('unknown');if(!['image/png','image/jpeg','image/webp'].includes(file.type)){setError('Подойдут JPG, PNG или WebP. HEIC сначала сохраните в JPEG.');return}if(file.size>20*1024*1024){setError('Файл больше 20 МБ. Уменьшите изображение.');return}setBusy(true);try{const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>60000000){bitmap.close();throw new Error('Очень большое изображение. Уменьшите его до 60 Мп или меньше.')}const scale=Math.min(1,1024/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d',{willReadFrequently:true});if(!ctx)throw new Error('Не удалось прочитать фото.');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();setImage(canvas.toDataURL('image/jpeg',.86));await new Promise(r=>setTimeout(r,30));const result=analyzeGearImage(ctx.getImageData(0,0,canvas.width,canvas.height));setAnalysis(result);if(result.toothCount)setTeeth(String(result.toothCount));}catch(e){setError(e instanceof Error?e.message:'Не удалось открыть файл.')}finally{setBusy(false)}};
 const result=deriveMeasuredSpurParameters({toothCount:Number(teeth),outsideDiameterMm:Number(diameter),confirmedExternalSpur:type==='spur',confirmedStandardFullDepth:standard,confirmedZeroProfileShift:standard,confirmedTipCircleDiameter:measured});
 const apply=()=>{if(!result.ok)return;if(!(Number(width)>0&&Number(bore)>=0)){setError('Укажите положительную ширину и неотрицательный диаметр отверстия.');return;}onApply({kind:'spur',teeth:Number(teeth),module:result.moduleMm,pressureAngleDeg:20,profileShift:0,width:Number(width),bore:Number(bore)},'Фото + измерение: стандартная эвольвента 20°, x = 0 подтверждены пользователем.');};
 return <div className="photo-wizard"><input ref={fileInput} aria-label="Загрузить фото колеса" className="visually-hidden" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>loadFile(e.target.files?.[0])}/><button className={`upload-zone ${image?'with-image':''}`} onClick={()=>fileInput.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void loadFile(e.dataTransfer.files[0])}} disabled={busy}>{image?<img src={image} alt="Загруженный образец для анализа контура"/>:<><Camera size={27}/><strong>Добавьте фото колеса</strong><span>Перетащите сюда или выберите файл</span></>}<span className="upload-caption"><Upload size={14}/>{image?'Заменить фото':'JPG, PNG, WebP · до 20 МБ'}</span></button><p className="field-help">Снимите торец строго сверху на однотонном фоне. Колесо должно целиком помещаться в кадре.</p><p className="privacy-note">Фото обрабатывается на устройстве.</p>{busy&&<p className="inline-status" role="status">Анализируем контур…</p>}{error&&<p className="inline-error" role="alert">{error}</p>}
 {analysis&&<div className="photo-result"><span className="photo-result-title"><ScanLine size={17}/>{analysis.toothCount?'На контуре найдены зубья':'Нужно уточнение'}</span>{analysis.toothCount&&<strong>{analysis.toothCount}<small> предполагаемых зубьев</small></strong>}<p>{analysis.candidateTypes[0]?.evidence||'По этому снимку нельзя уверенно определить деталь.'}</p><details><summary>Что удалось определить</summary><ul>{analysis.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul><p>Качество сигнала: {Math.round(analysis.confidence*100)}/100. Это оценка контура, а не вероятность правильной детали.</p></details></div>}
 <div className="expert-heading"><span className="section-number">?</span><h3>Уточним как инженер</h3></div><label className="field-label" htmlFor="photo-type">1. Какие зубья у детали?</label><Select value={type} onValueChange={setType}><SelectTrigger id="photo-type" className="select-control"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="unknown">Пока не знаю</SelectItem><SelectItem value="spur">Прямые, снаружи цилиндра</SelectItem><SelectItem value="helical">Наклонные</SelectItem><SelectItem value="herringbone">Шевронные, буквой V</SelectItem><SelectItem value="internal">Внутри кольца</SelectItem><SelectItem value="rack">На прямой рейке</SelectItem><SelectItem value="other">Конус, червяк или другой тип</SelectItem></SelectContent></Select>{type!=='spur'&&type!=='unknown'&&<div className="expert-note"><p>{type==='other'?'Для этого зацепления нужны данные пары и вид сбоку. Откройте справочник с перечнем исходных данных.':'Для такого типа одного наружного диаметра недостаточно. Нужны угол наклона или размеры внутренних зубьев; значения можно задать вручную.'}</p><button className="inline-link" onClick={onManual}>Перейти к параметрам <ArrowRight size={14}/></button></div>}
 <div className="input-grid photo-inputs"><label>2. Число зубьев <em>z</em><input aria-label="Число зубьев на фото" type="number" min="6" max="250" value={teeth} onChange={e=>setTeeth(e.target.value)} placeholder="24"/></label><label>3. Диаметр <em>da, мм</em><input aria-label="Измеренный диаметр вершин" type="number" min="0" step=".01" value={diameter} onChange={e=>setDiameter(e.target.value)} placeholder="52,00"/></label></div><p className="field-help">Диаметр окружности по вершинам зубьев. Пиксели не задают размер в миллиметрах.</p>
 <label className="check-row"><Checkbox checked={standard} onCheckedChange={v=>setStandard(v===true)}/><span>Подтверждаю: эвольвента 20°, стандартная высота, смещение x = 0.</span></label><label className="check-row"><Checkbox checked={measured} onCheckedChange={v=>setMeasured(v===true)}/><span>Измерен диаметр окружности вершин; при нечётном числе зубьев учтён способ измерения.</span></label>
 {result.ok&&<div className="module-result"><span>Расчётный модуль</span><strong>{result.moduleMm.toLocaleString('ru-RU',{maximumFractionDigits:5})} мм</strong><code>m = da / (z + 2)</code><p>По подтверждённым вами условиям. Без округления до стандартного ряда.</p></div>}
 <details className="photo-axial"><summary>4. Ширина и отверстие</summary><div className="input-grid"><label>Ширина, мм<input aria-label="Ширина по образцу" type="number" value={width} onChange={e=>setWidth(e.target.value)}/></label><label>Отверстие, мм<input aria-label="Отверстие по образцу" type="number" value={bore} onChange={e=>setBore(e.target.value)}/></label></div><p className="field-help">По умолчанию 10 и 8 мм — замените измерениями.</p></details>
 <button className="primary-button full" onClick={apply} disabled={!result.ok||busy}><Check size={16}/> Применить параметры</button>{!result.ok&&<p className="field-help">Модуль появится после измерения и подтверждения условий. Если они неизвестны — нужны чертёж или ответное колесо.</p>}
 {analysis&&<details className="expert-more"><summary>Какие ещё данные нужны?</summary>{analysis.expertQuestions.filter(q=>['profile','axial_dimensions','mate','use'].includes(q.id)).map(q=><div key={q.id}><strong>{q.label}</strong><p>{q.reason}</p></div>)}</details>}</div>
}
