"use client";
import {useMemo,useState} from 'react';
import {Check,AlertTriangle,X,Download,Printer} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {toast} from 'sonner';
import type {MeshValidation} from '@/lib/gearMath';
import {modelDimensionsForReport,modelSpatialGeometryForReport,type ModelMesh} from '@/lib/model';
import {downloadBlob} from '@/lib/download';
import {assessPrint,defaultPrintSettings,type PrintSettings} from '@/lib/printability';
export function PrintDialog({open,onOpenChange,mesh,validation}:{open:boolean;onOpenChange:(b:boolean)=>void;mesh:ModelMesh|null;validation:MeshValidation|null}){
 const [settings,setSettings]=useState(defaultPrintSettings);const result=useMemo(()=>{try{return mesh&&validation?{data:assessPrint(mesh,validation,settings),error:null}:{data:null,error:'Сначала задайте корректную геометрию.'}}catch(e){return {data:null,error:e instanceof Error?e.message:'Ошибка настроек.'}}},[mesh,validation,settings]);
 function setNumber(key:keyof PrintSettings,n:number){setSettings(s=>({...s,[key]:n}))}
 function exportJob(){
  if(!result.data||!mesh)return;
  try{
   const data={schema:'zatseplenie.print-brief.v5',appVersion:'0.7.0',createdAt:new Date().toISOString(),units:'mm',parameters:mesh.params,dimensions:modelDimensionsForReport(mesh),wormDimensions:'wormDimensions' in mesh?mesh.wormDimensions:null,cycloidalDimensions:'cycloidalDimensions' in mesh?mesh.cycloidalDimensions:null,cycloidalDiagnostics:'cycloidalDiagnostics' in mesh?mesh.cycloidalDiagnostics:null,bevelDimensions:'bevelDimensions' in mesh?mesh.bevelDimensions:null,bevelDiagnostics:'bevelDiagnostics' in mesh?mesh.bevelDiagnostics:null,spatialGeometry:modelSpatialGeometryForReport(mesh),internalCutterGeometry:mesh.internalCutterGeometry??null,internalRootDiagnostics:mesh.profile.internalRootDiagnostics??null,settings,assessment:result.data,geometryWarnings:mesh.warnings,customerInputRequired:['Назначение: макет / рабочая передача','Крутящий момент, обороты и срок службы','Температура, смазка, ответная деталь','Посадки и допуски по чертежу','Пробная печать и проверка сопряжения'],orderStatus:'Файл задания. Заказ не отправлен.'};
   downloadBlob(JSON.stringify(data,null,2),'application/json',`gear-print-brief-${mesh.params.kind}.json`);
   toast.success('Скачивание задания запрошено. Проверьте загрузки браузера.');
  }catch(e){toast.error(e instanceof Error?e.message:'Не удалось подготовить задание.');}
 }
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="engineering-dialog print-dialog"><DialogHeader><div className="dialog-kicker"><Printer size={17}/> ПОДГОТОВКА К ИЗГОТОВЛЕНИЮ</div><DialogTitle>Можно ли напечатать эту деталь?</DialogTitle><DialogDescription>Проверим геометрию для FDM. Нагрузку и ресурс оценивают отдельно.</DialogDescription></DialogHeader><div className="print-dialog-grid"><section><h3>Ваш принтер</h3><div className="input-grid"><Num label="Стол X, мм" value={settings.bedX} change={v=>setNumber('bedX',v)}/><Num label="Стол Y, мм" value={settings.bedY} change={v=>setNumber('bedY',v)}/><Num label="Высота Z, мм" value={settings.bedZ} change={v=>setNumber('bedZ',v)}/><Num label="Сопло, мм" value={settings.nozzle} step={.1} change={v=>setNumber('nozzle',v)}/><Num label="Линия, мм" value={settings.lineWidth} step={.01} change={v=>setNumber('lineWidth',v)}/><Num label="Слой, мм" value={settings.layer} step={.02} change={v=>setNumber('layer',v)}/></div><label className="field-label material-label" htmlFor="material">Материал пробной детали</label><Select value={settings.material} onValueChange={v=>setSettings(s=>({...s,material:v}))}><SelectTrigger id="material" className="select-control"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="PLA">PLA — проверка формы</SelectItem><SelectItem value="PETG">PETG — пробная деталь</SelectItem><SelectItem value="PA">PA — по профилю производителя</SelectItem><SelectItem value="PA-CF">PA-CF — износостойкое сопло</SelectItem></SelectContent></Select><p className="field-help">Температуры, сушка и поверхность стола — по паспорту конкретной марки материала.</p></section><section className="print-checks">{result.error&&<p className="inline-error">{result.error}</p>}{result.data&&<><div className={`print-verdict ${result.data.status}`}><strong>{result.data.status==='fail'?'Нужны изменения':result.data.status==='warning'?'Пробная печать с оговорками':'Геометрически подходит'}</strong><p>{result.data.disclaimer}</p></div>{result.data.checks.map(c=><div className={`print-check ${c.status}`} key={c.id}>{c.status==='pass'?<Check size={18}/>:c.status==='fail'?<X size={18}/>:<AlertTriangle size={18}/>}<div><strong>{c.label}</strong><p>{c.detail}</p></div></div>)}</>}</section></div><div className="dialog-action-row"><p>Сохраните задание вместе с STL для печати у себя или передачи исполнителю. Заказ автоматически не отправляется.</p><button className="primary-button" disabled={!result.data} onClick={exportJob}><Download size={16}/>Скачать задание</button></div></DialogContent></Dialog>
}
function Num({label,value,change,step=1}:{label:string;value:number;change:(v:number)=>void;step?:number}){return <label>{label}<input type="number" min=".01" step={step} value={Number.isFinite(value)?value:''} onChange={e=>change(e.target.value===''?NaN:Number(e.target.value))}/></label>}
